// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChEnY7scEFIV_azQ2Re07HOezxpv3tZVA',
    appId: '1:405062097549:web:6970a991b8218983db20c4',
    messagingSenderId: '405062097549',
    projectId: 'pokemon-card-68a6a',
    authDomain: 'pokemon-card-68a6a.firebaseapp.com',
    storageBucket: 'pokemon-card-68a6a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkmeYRD1ggCZh8auxru9IlZmF397v9RRo',
    appId: '1:405062097549:android:dd6de77ac9ca9c90db20c4',
    messagingSenderId: '405062097549',
    projectId: 'pokemon-card-68a6a',
    storageBucket: 'pokemon-card-68a6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzv_vgW1aqq7FAnhGERouDeAU1QNz2qgs',
    appId: '1:405062097549:ios:66b723dce2c53608db20c4',
    messagingSenderId: '405062097549',
    projectId: 'pokemon-card-68a6a',
    storageBucket: 'pokemon-card-68a6a.appspot.com',
    iosBundleId: 'com.example.pokemon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzv_vgW1aqq7FAnhGERouDeAU1QNz2qgs',
    appId: '1:405062097549:ios:66b723dce2c53608db20c4',
    messagingSenderId: '405062097549',
    projectId: 'pokemon-card-68a6a',
    storageBucket: 'pokemon-card-68a6a.appspot.com',
    iosBundleId: 'com.example.pokemon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChEnY7scEFIV_azQ2Re07HOezxpv3tZVA',
    appId: '1:405062097549:web:a68704f821cfd54ddb20c4',
    messagingSenderId: '405062097549',
    projectId: 'pokemon-card-68a6a',
    authDomain: 'pokemon-card-68a6a.firebaseapp.com',
    storageBucket: 'pokemon-card-68a6a.appspot.com',
  );
}
